config/routes.rb
Rails.application.routes.draw do
  resources :fixes, except: [:edit, :update] do
  	resource :reviews, only: [:create, :new, :destroy]
  	member do
  		put 'attend'
  	end
  end
  get '/profile/:id', to: 'users#show', as: 'profile'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/problems', to: 'pages#problems'
  get '/help', to: 'pages#help'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fix.rb
class Fix < ApplicationRecord
  belongs_to :requester, :class_name => 'User'
  belongs_to :mechanical, :class_name => 'User', optional: true
  has_one :review
  # reverse_geocoded_by :latitude, :longitude

  # after_validation :reverse_geocode
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :fix

  def owner
  	self.fix.requester
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :fixes
  has_many :user_fixes, foreign_key: "mechanical_id", :class_name => "Fix"
  has_many :reviews, through: :user_fixes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :mechanical])
  end
end

app/controllers/fixes_controller.rb
class FixesController < ApplicationController
  before_action :set_fix, only: [:show, :edit, :update, :destroy, :attend]
  before_action :authenticate_user!, except: [:new]
  # GET /fixes
  # GET /fixes.json
  def index
    if(current_user.mechanical) #Caso o usuário atual não seja mêcânico
      @myFixes = Fix.where mechanical: current_user
      @waitingFixes = Fix.where status: 0
    else
      @myFixes = Fix.where(requester: current_user).where.not(status: 2)
      @waitingFixes = Fix.where(status: 2).joins("LEFT OUTER JOIN reviews ON reviews.fix_id = fixes.id").where("reviews.id IS null")
    end
  end

  # GET /fixes/1
  # GET /fixes/1.json
  def show
  end

  # GET /fixes/new
  def new
    if current_user&.mechanical
      redirect_to fixes_path
    end
    @fix = Fix.new
  end

  # GET /fixes/1/edit
  def edit
  end

  # POST /fixes
  # POST /fixes.json
  def create
    @fix = Fix.new(fix_params)
    @fix.time = Time.now
    @fix.status = 0
    @fix.requester_id = current_user.id
    respond_to do |format|
      if @fix.save
        format.html { redirect_to @fix, notice: 'Fix was successfully created.' }
        format.json { render :show, status: :created, location: @fix }
      else
        format.html { render :new }
        format.json { render json: @fix.errors, status: :unprocessable_entity }
      end
    end
  end

  def attend
    if @fix.status == 0 && current_user&.mechanical
      @fix.status = 1
      @fix.mechanical = current_user
      respond_to do |format|
        if @fix.save
          format.html { redirect_to @fix, notice: 'O usuário foi alertado e aguarda sua chegada!' }
          format.json { render :show, status: :ok, location: @fix }
        else
          format.html { render :show }
          format.json { render json: @fix.errors, status: :unprocessable_entity }
        end
      end
    elsif @fix.status == 1 && !current_user&.mechanical
      @fix.status = 2
      respond_to do |format|
        if @fix.save
          format.html { redirect_to @fix, notice: 'O usuário foi alertado e aguarda sua chegada!' } #Redirecionar para review
          format.json { render :show, status: :ok, location: @fix }
        else
          format.html { render :show }
          format.json { render json: @fix.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /fixes/1
  # PATCH/PUT /fixes/1.json
  def update
    respond_to do |format|
      if @fix.update(fix_params)
        format.html { redirect_to @fix, notice: 'Fix was successfully updated.' }
        format.json { render :show, status: :ok, location: @fix }
      else
        format.html { render :edit }
        format.json { render json: @fix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixes/1
  # DELETE /fixes/1.json
  def destroy
    if @fix.requester == current_user && @fix.status != 2
      @fix.destroy
      respond_to do |format|
        format.html { redirect_to fixes_url, notice: 'Fix was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to fixes_url, notice: 'Você não pode deletar esta solicitação.' }
        format.json { head :unauthorized }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fix
      @fix = Fix.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fix_params
      params.require(:fix).permit(:requester_id, :mechanical_id, :latitude, :longitude, :status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		if current_user&.mechanical
			redirect_to fixes_url
		end
	end

	def problems
	end
	
	def help
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    # @reviews = Reviews.find(params[:fix_id]).reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.fix = Fix.find(params[:fix_id])
    respond_to do |format|
      if @review.save
        format.html { redirect_to profile_url(@review.fix.mechanical), notice: 'Review registrado com sucesso! Obrigado por contribuir!' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to fix_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:avaliation, :comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user
	def show
		@reviews = []
		@reviews = @user.reviews if @user.mechanical
	end

	private

	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixes_helper.rb
module FixesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fixes/_form.html.erb
<%= form_with(model: fix, local: true, class: "form-inline") do |form| %>
  <% if fix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fix.errors.count, "error") %> prohibited this fix from being saved:</h2>

      <ul>
      <% fix.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="form-group">
      <%= form.number_field :latitude, id: :fix_latitude, step: :any, style: "margin-bottom:8px;background-color:rgb(255,255,255);", placeholder: "Latitude", class:"form-control" %>
      <%= form.number_field :longitude, id: :fix_longitude, step: :any, style: "margin-bottom:8px;background-color:rgb(255,255,255);", placeholder: "Latitude", class:"form-control" %>
    </div>
  </div>
  <div class="col-md-12">
    <div class="form-group">
      <%= form.submit "SOLICITAR", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/fixes/edit.html.erb
<h1>Editing Fix</h1>

<%= render 'form', fix: @fix %>

<%= link_to 'Show', @fix %> |
<%= link_to 'Back', fixes_path %>

app/views/fixes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Fixes</h1>

<table>
  <thead>
    <tr>
      <th>Requester</th>
      <th>Mechanical</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Status</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myFixes.each do |fix| %>
      <tr>
        <td><%= fix.requester.email %></td>
        <td><%= fix.mechanical.email if fix.mechanical.present? %></td>
        <td><%= fix.latitude %></td>
        <td><%= fix.longitude %></td>
        <td><%= fix.status %></td>
        <td><%= fix.time %></td>
        <td><%= link_to 'Show', fix %></td>
        <% if fix.requester == current_user %>
          <td><%= link_to 'Destroy', fix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>Waiting Fixes</h1>

<table>
  <thead>
    <tr>
      <th>Requester</th>
      <th>Mechanical</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Status</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitingFixes.each do |fix| %>
      <tr>
        <td><%= fix.requester.email %></td>
        <td><%= fix.mechanical.email if fix.mechanical.present? %></td>
        <td><%= fix.latitude %></td>
        <td><%= fix.longitude %></td>
        <td><%= fix.status %></td>
        <td><%= fix.time %></td>
        <td><%= link_to 'Show', fix %></td>
        <% if fix.requester == current_user %>
          <td><%= link_to 'Avaliar', new_fix_reviews_path(fix) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Fix', new_fix_path unless current_user&.mechanical %>

app/views/fixes/new.html.erb
<div class="newsletter-subscribe" style="font-family:Montserrat, sans-serif;background-color:#eaeaea;">
	<div class="container">
		<div class="intro">
				<h2 class="text-center">Entrar com localização</h2>
				<p class="text-center">Digite sua latitude e longitude</p>
		</div>
		<%= render 'form', fix: @fix %>
		<%= link_to 'Voltar', fixes_path %>
	</div>
</div>

app/views/fixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requester:</strong>
  <%= @fix.requester.email %>
</p>
<% if @fix.mechanical.present? %>
  <p>
    <strong>Mechanical:</strong>
    <%= @fix.mechanical.email %>
  </p>
<% end %>

<p>
  <strong>Latitude:</strong>
  <%= @fix.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @fix.longitude %>
</p>

<p>
  <strong>Status:</strong>
  <%= @fix.status %>
</p>

<p>
  <strong>Time:</strong>
  <%= @fix.time %>
</p>

<% if current_user&.mechanical && @fix.status == 0 %>
  <%= link_to 'Aceitar Pedido', attend_fix_path(@fix), method: :put %> <br/>
<% end %>

<% if !current_user&.mechanical && @fix.status == 1 %>
  <%= link_to 'Marcar pedido como atendido', attend_fix_path(@fix), method: :put %> <br />
<% end %>
<%= link_to 'Back', fixes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fix My Car</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/help.html.erb
<div class="features-boxed" style="background-color:rgb(245,245,245);">
	<div class="container">
		<div class="intro">
			<h2 class="text-center">Selecionar tipo de Ajuda</h2>
		</div>
		<div class="row features" style="padding-top:20px;">
			<div class="col-lg-offset-2 col-md-offset-2 col-md-4 col-sm-6 col-xs-6 item">
				<a href="/problems">
					<div class="box">
						<%= image_tag("mecanica.png", style:"max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Tentar resolver problema</h3>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/fixes/new">
					<div class="box">
						<%= image_tag("mecanico.png", style:"max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Solicitar um Mecânico</h3>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<div class="features-boxed" style="background-color:rgb(245,245,245);">
	<div class="container">
		<div class="intro">
				<h2 class="text-center">Selecione o Serviço</h2>
		</div>
		<div class="row features" style="padding-top:20px;">
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/help">
					<div class="box">
						<%= image_tag("motor.png", style: "max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Motor</h3>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/help">
					<div class="box">
						<%= image_tag("rueda.png", style: "max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Borracharia</h3>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/help">
					<div class="box">
						<%= image_tag("saltador.png", style: "max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Elétrico</h3>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/fixes/new">
					<div class="box">
						<%= image_tag("coche.png", style: "max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Lavagem</h3>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/fixes/new">
					<div class="box">
						<%= image_tag("asiento.png", style: "max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Estofado</h3>
					</div>
				</a>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-6 item">
				<a href="/help">
					<div class="box">
						<%= image_tag("puerta.png", style: "max-width:90px;") %>
						<h3 class="name" style="margin-top:8px;display:flex;justify-content:center;color:rgb(49,52,55);">Lataria</h3>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

app/views/pages/problems.html.erb
<div class="highlight-clean" style="font-family:Montserrat, sans-serif;background-color:#eeeeee">
	<div class="container">
		<div class="intro">
			<h2 class="text-center" style="margin-bottom:40px;">Avaliar problema</h2>
			<p class="text-center" style="font-size:22px;font-weight:bold;background-color:#cccccc;border-radius:10px;padding-top:10px;padding-bottom:10px;color:#484848">Seu motor parou de funcionar devido a algum acidente?</p>
			<!--Abra o capô e verifique se os cabos da bateria estão devidamente ligados. Você checou os cabos?-->
			<!--A ajuda foi suficiente para resolver seu problema?-->
			<!--Solicitar a ajuda de um mecânico especializado?-->
			<!--Você deseja chamar um serviço de guincho para rebocar o veículo?-->
			<!--Você ficou satisfeito com o resultado da ajuda?-->
		</div>
		<div class="buttons"><a class="btn btn-primary" role="button" href="/fixes/new" style="background-color:rgb(7,174,64);">Sim</a><a class="btn btn-primary" role="button" href="/fixes/new" style="background-color:rgb(217,0,0);">Não</a></div>
	</div>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true, url: fix_reviews_path, style: "background-color:rgba(255,255,255,0);") do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2 class="text-center">Avaliação</h2>
  <div class="form-group">
    <%= form.text_area :comment, id: :review_comment, rows: "14", name: "message", placeholder: "Deixar um comentário", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= form.number_field :avaliation, id: :review_avaliation, class: "form-control", placeholder: "Avaliar mecânico", min: "1", max: "5", step: "1" %>
  </div>
  <div class="form-group" style="display:flex;justify-content:center;">
    <%= form.submit "ENVIAR", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Avaliation</th>
      <th>Comment</th>
      <th>Fix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.avaliation %></td>
        <td><%= review.comment %></td>
        <td><%= review.Fix %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="contact-clean" style="background-color:#e7e7e7;">
	<%= render 'form', review: @review %>
	<div class="container">
		<%= link_to 'Voltar', fixes_path %>
	</div>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avaliation:</strong>
  <%= @review.avaliation %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Fix:</strong>
  <%= @review.Fix %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/shared/_footer.html.erb
<div class="footer-dark">
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-push-6 item text">
					<h3>Fix My Car</h3>
					<p class="text-justify">Deu problema no seu automóvel e você não faz a menor ideia do que aconteceu e também não sabe onde o manual foi parar? O Fix My Car é um app que promete inovar na assistência do seu carro.<br></p>
				</div>
				<div class="col-md-3 col-md-pull-6 col-sm-4 item">
					<h3>Serviços</h3>
					<ul>
						<li><a href="/help">Motor</a></li>
						<li><a href="/help">Borracharia</a></li>
						<li><a href="/help">Elétrico</a></li>
						<li><a href="/">Mais</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-md-pull-6 col-sm-4 item">
					<h3>Sobre</h3>
					<ul>
						<li><a href="#">A Empresa</a></li>
						<li><a href="#">Equipe</a></li>
						<li><a href="#">Trabalhe conosco</a></li>
					</ul>
				</div>
				<div class="col-md-12 col-sm-4 item social"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-snapchat-ghost"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
			</div>
			<p class="copyright">Fix My Car © 2018</p>
		</div>
	</footer>
</div>

app/views/shared/_navbar.html.erb
<div>
  <div class="header-dark" style="padding-bottom:0px;min-height:83px;">
    <nav class="navbar navbar-default navigation-clean-search" style="font-family:Montserrat, sans-serif;background-color:rgba(72,72,72,0.85);min-height:83px;">
      <div class="container">
        <div class="navbar-header"><a class="navbar-brand" href="/">
          <%= image_tag("logo.png", class: "img-responsive", width: "200px", style: "margin-top: -13px;") %>
        </a><button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button></div>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav">
            <li class="dropdown" style="font-weight:bold;"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#" style="font-size:15px;">Serviços&nbsp;<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li role="presentation"><a href="/help" style="font-weight:bold;font-size:15px;">Motor</a></li>
                <li role="presentation"><a href="/help" style="font-weight:bold;font-size:15px;">Borracharia</a></li>
                <li role="presentation"><a href="/help" style="font-weight:bold;font-size:15px;">Elétrico</a></li>
                <li role="presentation"><a href="/" style="font-weight:bold;font-size:15px;">Mais</a></li>
              </ul>
            </li>
          </ul>
          <% if !user_signed_in? %>
            <p class="navbar-text navbar-right"><%= link_to "Entrar", new_user_session_path, class: "navbar-link login", style: "font-weight:bold;font-size:15px;" %>
              <%= link_to "Cadastrar-se", new_user_registration_path, class: "btn btn-default action-button", role: "button", style: "font-weight:bold;font-size:15px;" %>
            </p>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown" style="font-weight:bold;"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#" style="font-size:15px;">Configurações&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li role="presentation"><%= link_to "Painel de controle", fixes_path, style: "font-weight:bold;font-size:15px;" %></li>
                  <li role="presentation"><%= link_to "Editar Perfil", edit_user_registration_path, style: "font-weight:bold;font-size:15px;" %></li>
                  <li role="presentation"><%= link_to "Sair", destroy_user_session_path, style: "font-weight:bold;font-size:15px;", method: :delete %></li>
                </ul>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<h1 class="mx-auto">Reviews</h1>
</div>

<div>
	<div>
		<p>Nome: <%= @user.name %></p>

	</div>
	<hr/>
	<div>
		<% @reviews.each do |review| %>
			<p>Usuário: <%= review.owner.name %></p>
			<p>Nota: <%= review.avaliation %></p>
			<p>Comentário: <%= review.comment %></p>
			<hr />
		<% end %>
	</div>
</div>